name: Bump & Tag & Release Action
description: Common GitHub Action for bumping, tagging, and releasing

inputs:
  githubToken:
    description: 'The GitHub token to use for authentication'
    required: true
    default: ''
  slackChannelId:
    description: 'The Slack channel to post to'
    required: true
    default: ''
  slackBotToken:
    description: 'The Slack bot token'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Configure GitHub credentials
      shell: bash
      run: git config --global url."https://${{ inputs.githubToken }}@github.com/".insteadOf "https://github.com/"

    - name: Set repository name to variable
      shell: bash
      run: echo "PROJECT_SHORT_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV

    - name: Bump and Tag
      id: bump_and_tag
      uses: bricklanetech/action.bump-version-and-tag@v3
      with:
        prefix: 'v'

    - name: Move 'latest' tag to current commit ref
      uses: EndBug/latest-tag@latest

    - name: Move SemVer major & minor tags automatically
      uses: kellyselden/move-semver-tags-action@v3

    - name: Create changelog text
      id: github_release
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{ inputs.githubToken }}
        config_file: .github/tag-changelog-config.js

    - name: Create and publish release
      uses: ncipollo/release-action@v1
      with:
        body: ${{steps.github_release.outputs.changelog}}
        tag: ${{ steps.bump_and_tag.outputs.tag }}

    - name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ inputs.slackChannelId }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ env.PROJECT_SHORT_NAME }} ${{ steps.bump_and_tag.outputs.tag }}* has been released by ${{ github.actor }} :rocket:"
                }
              }
            ],
            "attachments": [
              {
                "color": "#2eb886",
                "text": ${{ toJSON(steps.github_release.outputs.changelog) }}
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slackBotToken }}
