---
name: Push workflow for release branches

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    name: Bump and Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set repository name to variable PROJECT_SHORT_NAME
        shell: bash -e {0}
        run: echo "PROJECT_SHORT_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Configure GitHub credentials
        shell: bash -e {0}
        run: git config --global url."https://${{ env.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Bump and Tag
        id: bump_and_tag
        uses: propertylift/action.bump-version-and-tag@v3
        with:
          prefix: 'v'

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and publish release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag: ${{ steps.bump_and_tag.outputs.tag }}

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_NOTIFICATION }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ env.PROJECT_SHORT_NAME }} ${{ steps.bump_and_tag.outputs.tag }}* has been released :rocket:"
                  }
                }
              ],
              "attachments": [
                {
                  "color": "#2eb886",
                  "text": ${{ toJSON(steps.github_release.outputs.changelog) }}
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
